engines:
  phpmd:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php:
ratings:
  paths:
  - "src/**/*"
  - "MailCatcher.php"
exclude_paths:
- "src/WP_List_Table.php"
- "assets/*"
- "build/**/*"
